name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.3
homepage: https://github.com/ZaraclaJ/audio_recorder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.4"

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  file: ^6.1.1

flutter:
  plugin:
    androidPackage: com.jordanalcaraz.audiorecorder.audiorecorder
    pluginClass: AudioRecorderPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.6
  path_provider: ^2.0.0
